import { Check, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

const plans = [
  {name:'Standard',price:'€59',target:'Dla małych sklepów',cta:'Wybierz Standard',features:['1 sklep, do 5 użytkowników','Do 5 000 SKU i EAN','Partie, daty ważności i FEFO','Dostawy i zamówienia','Straty, skaner i inwentaryzacja','Podstawowe alerty i raporty','CSV i Open Food Facts']},
  {name:'Pro',price:'€119',target:'Inteligentny pojedynczy sklep',cta:'Wybierz Pro',popular:true,features:['Wszystko ze Standard','Do 15 użytkowników i 25 000 SKU','Shelf Mode i Task Management+','FreshStock Today i Smart Markdown','AI Restock, Markdown i Waste','Savings i raporty zaawansowane','1 integracja POS realtime']},
  {name:'Business',price:'€249',target:'Dla małych i średnich sieci',cta:'Wybierz Business',features:['Wszystko z Pro','Do 5 sklepów i 50 użytkowników','Do 100 000 SKU','Centralny dashboard i transfery','Wiele POS i FreshStock Bridge','API i webhooks','RBAC, Audit Log i Traceability']},
  {name:'Enterprise',price:'Wycena indywidualna',target:'Konfiguracja per kontrakt',cta:'Skontaktuj się',features:['Negocjowane limity','Custom POS i API','SSO / SAML','Dedykowany onboarding','Custom Reports i SLA','ERP i księgowość','Priority Support i custom security']},
]
const compare=[['Inventory','FEFO i partie','✓','✓','✓','✓'],['Operations','Shelf Mode','—','✓','✓','✓'],['Intelligence','AI i Savings','—','✓','✓','✓'],['Integrations','POS realtime','—','1','Wiele','Custom'],['Management','Multi-store','—','—','5','Custom'],['Security','SSO / SAML','—','—','—','✓']]

export default function Pricing(){return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><Link to="/" className="flex items-center gap-2 text-xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-green-600 text-white">F</span>FreshStock</Link><Link to="/login" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Zaloguj się</Link></header><main className="mx-auto max-w-7xl px-5 pb-20"><section className="py-12 text-center"><p className="font-semibold text-green-700">PLANY FRESHSTOCK</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Mniej strat. Lepszy magazyn. Plan dopasowany do sklepu.</h1><p className="mx-auto mt-4 max-w-2xl text-lg text-gray-600">Zacznij od 14-dniowego trialu Pro. Twoje dane pozostają bezpieczne przy każdej zmianie planu.</p></section><div className="grid gap-5 lg:grid-cols-4">{plans.map(p=><article key={p.name} className={`relative flex flex-col rounded-3xl border bg-white p-6 shadow-sm ${p.popular?'border-green-500 ring-2 ring-green-200 lg:-translate-y-3':''}`}>{p.popular&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-green-600 px-3 py-1 text-xs font-bold text-white"><Sparkles className="mr-1 inline h-3 w-3"/>Najczęściej wybierany</span>}<h2 className="text-xl font-bold">{p.name}</h2><p className="mt-1 min-h-10 text-sm text-gray-500">{p.target}</p><p className="mt-5 text-3xl font-black">{p.price}{p.price.startsWith('€')&&<span className="text-sm font-normal text-gray-500"> / miesiąc</span>}</p><ul className="my-7 flex-1 space-y-3">{p.features.map(f=><li key={f} className="flex gap-2 text-sm"><Check className="h-5 w-5 shrink-0 text-green-600"/>{f}</li>)}</ul><Link to="/login" className={`rounded-xl px-4 py-3 text-center font-semibold ${p.popular?'bg-green-600 text-white':'border border-slate-300 hover:border-green-500'}`}>{p.cta}</Link></article>)}</div><section className="mt-16 overflow-hidden rounded-3xl border bg-white"><div className="p-6"><h2 className="text-2xl font-bold">Porównaj plany</h2><p className="text-gray-500">Najważniejsze różnice w jednym miejscu.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Grupa','Funkcja','Standard','Pro','Business','Enterprise'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{compare.map(r=><tr key={r[1]} className="border-t">{r.map((v,i)=><td key={i} className={`px-5 py-4 ${i===1?'font-semibold':''}`}>{v}</td>)}</tr>)}</tbody></table></div></section></main></div>}
