import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, ArrowRight, Check, LogOut, Store } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../hooks/useAuth'

const storeTypes: Record<string,string> = { GROCERY:'Sklep spożywczy', MINIMARKET:'Minimarket', SUPERMARKET:'Supermarket', BAKERY:'Piekarnia', BUTCHER:'Sklep mięsny', FRUIT_VEGETABLES:'Owoce i warzywa', DELICATESSEN:'Delikatesy', CONVENIENCE:'Sklep convenience', WHOLESALE:'Hurtownia', OTHER:'Inny' }
const locationOptions: Record<string,string> = { SALES_FLOOR:'Sala sprzedaży', MAIN_WAREHOUSE:'Magazyn główny', COLD_ROOM:'Chłodnia', FREEZER:'Mroźnia', BACKROOM:'Zaplecze', VEGETABLES_STORAGE:'Magazyn warzyw', DRINKS_STORAGE:'Magazyn napojów', OTHER:'Inna' }
const priorities: Record<string,string> = { EXPIRY_WASTE:'Straty przez terminy ważności', OVERSTOCK:'Nadmiar zapasu', STOCKOUTS:'Braki magazynowe', INVENTORY_COUNTING:'Inwentaryzacja', DELIVERY_PROBLEMS:'Problemy z dostawami', WASTE:'Straty', ORDERING:'Zamawianie', STORE_OPERATIONS:'Organizacja sklepu' }
const titles = ['Typ sklepu','Informacje o sklepie','Lokalizacje zapasu','Kontrola terminów','Kolejność sprzedaży','Sugestie przecen','Dostawy','Sprzedaż i POS','Produkty','Dostawcy','Użytkownicy','Alerty','Priorytety firmy','Podsumowanie']
const defaults: any = {
  1:{}, 2:{country:'PL',currency:'PLN',timezone:'Europe/Warsaw',language:'pl'}, 3:{locations:[]},
  4:{preset:'STANDARD',expiry_rules:[7,3,1]}, 5:{fefo_enabled:true}, 6:{enabled:true,rules:[{days:7,discount:10},{days:3,discount:25},{days:1,discount:50}]},
  7:{delivery_frequency:'SEVERAL_WEEK',require_expiry_on_receiving:'EXPIRY_MANAGED',batch_tracking:'OPTIONAL'}, 8:{sales_method:'NO_INTEGRATION'},
  9:{method:'START_EMPTY'}, 10:{mode:'SKIP'}, 11:{users:[]}, 12:{alert_rules:{EXPIRED_PRODUCTS:true,EXPIRY_DAYS:7,LOW_STOCK:true,OUT_OF_STOCK:true,DELIVERY_PROBLEMS:true,HIGH_WASTE:true,INVENTORY_DIFFERENCES:true},channels:['IN_APP']}, 13:{business_priorities:[]}, 14:{}
}

const Input = ({label,...props}:any) => <label className="block"><span className="text-sm font-medium text-gray-700">{label}</span><input {...props} className="mt-1 w-full rounded-xl border border-gray-300 px-3 py-2.5 outline-none focus:border-green-500 focus:ring-2 focus:ring-green-100" /></label>
const Select = ({label,children,...props}:any) => <label className="block"><span className="text-sm font-medium text-gray-700">{label}</span><select {...props} className="mt-1 w-full rounded-xl border border-gray-300 px-3 py-2.5 bg-white">{children}</select></label>
const Cards = ({options,value,onChange,multiple=false}:any) => <div className="grid sm:grid-cols-2 gap-3">{Object.entries(options).map(([key,label]:any)=>{const active=multiple?value?.includes(key):value===key;return <button type="button" key={key} onClick={()=>onChange(multiple?(active?value.filter((x:string)=>x!==key):[...(value||[]),key]):key)} className={`text-left p-4 rounded-xl border-2 transition ${active?'border-green-500 bg-green-50 text-green-800':'border-gray-200 hover:border-gray-300'}`}><span className="flex items-center justify-between font-medium">{label}{active&&<Check className="w-4 h-4"/>}</span></button>})}</div>

export default function StoreSetup({settingsMode=false}:{settingsMode?:boolean}) {
  const navigate=useNavigate(), queryClient=useQueryClient(), {logout}=useAuth()
  const {data,isLoading}=useQuery({queryKey:['onboarding'],queryFn:async()=>(await api.get('/onboarding')).data})
  const [step,setStep]=useState(1), [form,setForm]=useState<any>(defaults), [error,setError]=useState(''), [saving,setSaving]=useState(false)
  const lastSaved=useRef(''), hydrated=useRef(false)
  useEffect(()=>{if(!data)return;const next={...defaults,...data.step_data};const nextStep=settingsMode?1:(data.current_step||1);setStep(nextStep);setForm(next);lastSaved.current=JSON.stringify(next[nextStep]||{});hydrated.current=true},[data,settingsMode])
  const current=useMemo(()=>form[step]||{},[form,step]), set=(patch:any)=>setForm((x:any)=>({...x,[step]:{...x[step],...patch}}))
  useEffect(()=>{if(!hydrated.current)return;const serialized=JSON.stringify(current);if(serialized===lastSaved.current)return;const timer=setTimeout(()=>{api.put(`/onboarding/steps/${step}`,{data:current,complete:false,next_step:step}).then(()=>{lastSaved.current=serialized}).catch(()=>{})},900);return()=>clearTimeout(timer)},[current,step])
  const save=async(next?:number,finish=false,complete=true)=>{setSaving(true);setError('');try{const res=await api.put(`/onboarding/steps/${step}`,{data:current,complete,next_step:next});lastSaved.current=JSON.stringify(next?(form[next]||{}):current);queryClient.setQueryData(['onboarding'],res.data);if(finish){queryClient.invalidateQueries({queryKey:['onboarding-status']});navigate('/')}else if(next)setStep(next)}catch(e:any){setError(e.response?.data?.detail||'Nie udało się zapisać ustawień')}finally{setSaving(false)}}
  const saveAndExit=async()=>{setSaving(true);setError('');try{await api.put(`/onboarding/steps/${step}`,{data:current,complete:false,next_step:step});logout()}catch(e:any){setError(e.response?.data?.detail||'Nie udało się zapisać ustawień');setSaving(false)}}
  const summary=useMemo(()=>data?.settings||{},[data])
  if(isLoading)return <div className="min-h-screen grid place-items-center">Ładowanie konfiguracji…</div>
  return <div className="min-h-screen bg-gradient-to-br from-green-50 via-white to-emerald-50 px-4 py-6 sm:py-10">
    <div className="max-w-3xl mx-auto">
      <header className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-green-600 text-white grid place-items-center"><Store/></div><div><h1 className="text-xl font-bold">{settingsMode?'Konfiguracja sklepu':'Skonfiguruj swój sklep'}</h1><p className="text-sm text-gray-500">Krok {step} z 14 · {titles[step-1]}</p></div></div><button onClick={logout} className="text-sm text-gray-500 flex gap-2"><LogOut className="w-4"/> Wyloguj</button></header>
      <div className="h-2 bg-gray-200 rounded-full overflow-hidden mb-6"><div className="h-full bg-green-600 transition-all" style={{width:`${step/14*100}%`}}/></div>
      <section className="bg-white rounded-3xl border border-gray-200 shadow-sm p-5 sm:p-8 min-h-[430px]">
        <h2 className="text-2xl font-bold mb-2">{titles[step-1]}</h2><Step step={step} value={current} set={set} summary={summary} data={data}/>
        {error&&<p className="mt-4 text-sm bg-red-50 text-red-700 p-3 rounded-xl">{error}</p>}
      </section>
      <footer className="flex flex-wrap items-center justify-between gap-3 mt-5">
        <button disabled={step===1||saving} onClick={()=>setStep(step-1)} className="px-4 py-2.5 rounded-xl border bg-white disabled:opacity-40 flex gap-2"><ArrowLeft className="w-4"/> Wstecz</button>
        <div className="flex gap-2"><button disabled={saving} onClick={saveAndExit} className="px-4 py-2.5 text-gray-600">Zapisz i wyjdź</button><button disabled={saving} onClick={()=>save(step<14?step+1:undefined,step===14)} className="px-5 py-2.5 bg-green-600 text-white rounded-xl font-semibold flex gap-2 disabled:opacity-50">{saving?'Zapisywanie…':step===14?'Zakończ konfigurację':'Kontynuuj'}{step<14&&<ArrowRight className="w-4"/>}</button></div>
      </footer>
    </div>
  </div>
}

function Step({step,value,set,summary,data}:any){
  if(step===1)return <><p className="text-gray-500 mb-5">Jaki typ sklepu prowadzisz? Dopasujemy sugerowane ustawienia.</p><Cards options={storeTypes} value={value.business_type} onChange={(x:string)=>set({business_type:x})}/></>
  if(step===2)return <div className="grid sm:grid-cols-2 gap-4"><Input label="Nazwa sklepu *" value={value.store_name||''} onChange={(e:any)=>set({store_name:e.target.value})}/><Input label="Nazwa firmy" value={value.company_name||''} onChange={(e:any)=>set({company_name:e.target.value})}/><Input label="Adres" value={value.address||''} onChange={(e:any)=>set({address:e.target.value})}/><Input label="NIP / VAT" value={value.vat_number||''} onChange={(e:any)=>set({vat_number:e.target.value})}/><Input label="Kraj *" value={value.country||''} maxLength={2} onChange={(e:any)=>set({country:e.target.value.toUpperCase()})}/><Input label="Waluta *" value={value.currency||''} maxLength={3} onChange={(e:any)=>set({currency:e.target.value.toUpperCase()})}/><Input label="Strefa czasowa *" value={value.timezone||''} onChange={(e:any)=>set({timezone:e.target.value})}/><Select label="Język *" value={value.language||'pl'} onChange={(e:any)=>set({language:e.target.value})}><option value="pl">Polski</option><option value="en">English</option><option value="nl">Nederlands</option></Select><Input label="Powierzchnia sklepu (m²)" type="number" value={value.store_size||''} onChange={(e:any)=>set({store_size:e.target.value})}/><Input label="Liczba pracowników" type="number" value={value.employee_count||''} onChange={(e:any)=>set({employee_count:+e.target.value})}/><Input label="Przybliżona liczba SKU" type="number" value={value.approximate_sku_count||''} onChange={(e:any)=>set({approximate_sku_count:+e.target.value})}/><Input label="Liczba stanowisk POS" type="number" value={value.pos_count||''} onChange={(e:any)=>set({pos_count:+e.target.value})}/></div>
  if(step===3){const selected=(value.locations||[]).map((x:any)=>x.key);return <><p className="text-gray-500 mb-5">Gdzie przechowujesz produkty? Nazwy możesz zmienić.</p><Cards options={locationOptions} multiple value={selected} onChange={(keys:string[])=>set({locations:keys.map(k=>value.locations?.find((x:any)=>x.key===k)||{key:k,name:locationOptions[k]})})}/><div className="mt-4 space-y-2">{(value.locations||[]).map((x:any,i:number)=><Input key={x.key} label={locationOptions[x.key]} value={x.name} onChange={(e:any)=>{const a=[...value.locations];a[i]={...a[i],name:e.target.value};set({locations:a})}}/>)}</div></>}
  if(step===4)return <><p className="text-gray-500 mb-5">Kiedy FreshStock ma ostrzegać o zbliżającym się terminie?</p><Cards options={{BASIC:'Podstawowy — 3 dni',STANDARD:'Standard — 7 / 3 / 1',ADVANCED:'Zaawansowany — 14 / 7 / 3 / 1',CUSTOM:'Własne progi'}} value={value.preset} onChange={(x:string)=>set({preset:x,expiry_rules:x==='BASIC'?[3]:x==='STANDARD'?[7,3,1]:x==='ADVANCED'?[14,7,3,1]:value.expiry_rules})}/>{value.preset==='CUSTOM'&&<Input label="Progi w dniach, oddzielone przecinkami" value={(value.expiry_rules||[]).join(', ')} onChange={(e:any)=>set({expiry_rules:e.target.value.split(',').map(Number).filter(Number.isFinite)})}/>}</>
  if(step===5)return <><p className="text-gray-500 mb-5">FreshStock może sprzedawać najpierw produkty z najkrótszą datą. To sugestia — ustawienie możesz zmienić później.</p><Cards options={{YES:'Włącz kolejność według daty',NO:'Wyłącz'}} value={value.fefo_enabled?'YES':'NO'} onChange={(x:string)=>set({fefo_enabled:x==='YES'})}/></>
  if(step===6)return <><p className="text-gray-500 mb-5">System będzie tylko sugerował przeceny. Cena zmieni się dopiero po Twojej akceptacji.</p><Cards options={{YES:'Włącz sugestie',NO:'Wyłącz sugestie'}} value={value.enabled?'YES':'NO'} onChange={(x:string)=>set({enabled:x==='YES'})}/>{value.enabled&&<div className="mt-5 space-y-2">{(value.rules||[]).map((r:any,i:number)=><div key={i} className="grid grid-cols-2 gap-3"><Input label="Dni do terminu" type="number" value={r.days} onChange={(e:any)=>{const a=[...value.rules];a[i]={...r,days:+e.target.value};set({rules:a})}}/><Input label="Rabat %" type="number" value={r.discount} onChange={(e:any)=>{const a=[...value.rules];a[i]={...r,discount:+e.target.value};set({rules:a})}}/></div>)}</div>}</>
  if(step===7)return <div className="space-y-4"><Select label="Częstotliwość dostaw" value={value.delivery_frequency} onChange={(e:any)=>set({delivery_frequency:e.target.value})}><option value="DAILY">Codziennie</option><option value="SEVERAL_WEEK">Kilka razy w tygodniu</option><option value="WEEKLY">Co tydzień</option><option value="IRREGULAR">Nieregularnie</option></Select><Select label="Wymagać daty ważności przy odbiorze?" value={value.require_expiry_on_receiving} onChange={(e:any)=>set({require_expiry_on_receiving:e.target.value})}><option value="ALWAYS">Zawsze</option><option value="EXPIRY_MANAGED">Tylko dla produktów z kontrolą daty</option><option value="NEVER">Nigdy</option></Select><Select label="Śledzić numery partii?" value={value.batch_tracking} onChange={(e:any)=>set({batch_tracking:e.target.value})}><option value="ALWAYS">Zawsze</option><option value="OPTIONAL">Opcjonalnie</option><option value="DISABLED">Wyłączone</option></Select></div>
  if(step===8)return <><p className="text-gray-500 mb-5">Jak rejestrujesz sprzedaż?</p><Cards options={{FRESHSTOCK_POS:'FreshStock POS',EXTERNAL_POS:'Zewnętrzny POS',CSV_IMPORT:'Import CSV',NO_INTEGRATION:'Jeszcze bez integracji'}} value={value.sales_method} onChange={(x:string)=>set({sales_method:x,provider:undefined})}/>{value.sales_method==='EXTERNAL_POS'&&<div className="mt-5"><Cards options={{square:'Square',lightspeed:'Lightspeed',generic_rest:'Generic REST',local_bridge:'FreshStock Bridge',other:'Inny'}} value={value.provider} onChange={(x:string)=>set({provider:x})}/></div>}</>
  if(step===9)return <ProductImport value={value} set={set}/>
  if(step===10)return <><Cards options={{ADD:'Dodaj dostawcę',IMPORT:'Importuj dostawców',SKIP:'Pomiń'}} value={value.mode} onChange={(x:string)=>set({mode:x,supplier:x==='ADD'?(value.supplier||{}):undefined})}/>{value.mode==='ADD'&&<div className="grid sm:grid-cols-2 gap-4 mt-5"><Input label="Nazwa *" value={value.supplier?.name||''} onChange={(e:any)=>set({supplier:{...value.supplier,name:e.target.value}})}/><Input label="Email" value={value.supplier?.email||''} onChange={(e:any)=>set({supplier:{...value.supplier,email:e.target.value}})}/><Input label="Telefon" value={value.supplier?.phone||''} onChange={(e:any)=>set({supplier:{...value.supplier,phone:e.target.value}})}/><Input label="NIP / VAT" value={value.supplier?.vat_number||''} onChange={(e:any)=>set({supplier:{...value.supplier,vat_number:e.target.value}})}/></div>}</>
  if(step===11)return <Users value={value} set={set}/>
  if(step===12)return <><p className="text-gray-500 mb-4">Wybierz zdarzenia i kanały powiadomień.</p><div className="grid sm:grid-cols-2 gap-2">{Object.entries({EXPIRED_PRODUCTS:'Produkty przeterminowane',LOW_STOCK:'Niski stan',OUT_OF_STOCK:'Brak towaru',DELIVERY_PROBLEMS:'Problemy z dostawą',HIGH_WASTE:'Wysokie straty',INVENTORY_DIFFERENCES:'Różnice inwentaryzacyjne'}).map(([k,l])=><label key={k} className="p-3 border rounded-xl"><input type="checkbox" checked={!!value.alert_rules?.[k]} onChange={(e)=>set({alert_rules:{...value.alert_rules,[k]:e.target.checked}})}/> <span className="ml-2">{l}</span></label>)}</div><div className="flex gap-4 mt-5">{[['IN_APP','W aplikacji'],['EMAIL','Email'],['PUSH','Push']].map(([k,l])=><label key={k}><input type="checkbox" checked={value.channels?.includes(k)} onChange={(e)=>set({channels:e.target.checked?[...(value.channels||[]),k]:value.channels.filter((x:string)=>x!==k)})}/> {l}</label>)}</div></>
  if(step===13)return <><p className="text-gray-500 mb-5">Co jest obecnie największym problemem Twojego sklepu? Odpowiedź ustawi kolejność informacji na dashboardzie.</p><Cards options={priorities} multiple value={value.business_priorities||[]} onChange={(x:string[])=>set({business_priorities:x})}/></>
  return <div className="space-y-3"><p className="text-lg text-green-700 font-semibold">FreshStock jest gotowy.</p>{[['Typ sklepu',storeTypes[summary.business_type]||value.business_type],['Lokalizacje',`${data?.locations?.length||0} skonfigurowanych`],['Sprzedaż według daty',summary.fefo_enabled?'Włączona':'Wyłączona'],['Alerty terminów',(summary.expiry_rules||[]).join(' / ')||'—'],['Sugestie przecen',summary.markdown_suggestions_enabled?'Włączone':'Wyłączone'],['POS',summary.selected_pos_provider||summary.sales_method||'—'],['Użytkownicy','Role gotowe']].map(([a,b])=><div key={a} className="flex justify-between border-b py-3"><span className="text-gray-500">{a}</span><span className="font-medium flex gap-2"><Check className="w-4 text-green-600"/>{b}</span></div>)}</div>
}

function Users({value,set}:any){const add=()=>set({users:[...(value.users||[]),{email:'',full_name:'',role:'EMPLOYEE',password:''}]});return <><p className="text-gray-500 mb-4">Obecny użytkownik pozostanie właścicielem. Zaproś zespół teraz lub później.</p>{(value.users||[]).map((u:any,i:number)=><div key={i} className="grid sm:grid-cols-2 gap-3 border rounded-xl p-3 mb-3"><Input label="Imię i nazwisko" value={u.full_name} onChange={(e:any)=>{const a=[...value.users];a[i]={...u,full_name:e.target.value};set({users:a})}}/><Input label="Email" type="email" value={u.email} onChange={(e:any)=>{const a=[...value.users];a[i]={...u,email:e.target.value};set({users:a})}}/><Select label="Rola" value={u.role} onChange={(e:any)=>{const a=[...value.users];a[i]={...u,role:e.target.value};set({users:a})}}><option>MANAGER</option><option>WAREHOUSE</option><option>EMPLOYEE</option><option>VIEWER</option></Select><Input label="Hasło startowe (min. 12 znaków)" type="password" value={u.password} onChange={(e:any)=>{const a=[...value.users];a[i]={...u,password:e.target.value};set({users:a})}}/></div>)}<button onClick={add} className="px-4 py-2 border rounded-xl text-green-700">+ Zaproś użytkownika</button></>}

function ProductImport({value,set}:any){
  const [rows,setRows]=useState<any[]>([]),[preview,setPreview]=useState<any>(null),[message,setMessage]=useState('')
  const load=async(file:File)=>{const text=await file.text();const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return;const delimiter=lines[0].includes(';')?';':',';const headers=lines[0].split(delimiter).map(x=>x.trim().toLowerCase());const parsed=lines.slice(1).map(line=>{const cells=line.split(delimiter);return Object.fromEntries(headers.map((h,i)=>[h,cells[i]?.trim()||'']))});setRows(parsed);const res=await api.post('/onboarding/products/preview',{rows:parsed});setPreview(res.data)}
  const run=async()=>{const res=await api.post('/onboarding/products/import',{rows});setMessage(`Dodano ${res.data.created}, pominięto ${res.data.skipped}.`);setPreview({...preview,rows:res.data.rows})}
  return <><p className="text-gray-500 mb-5">Wybierz sposób rozpoczęcia pracy z katalogiem.</p><Cards options={{CSV_EXCEL:'Import CSV / Excel',FROM_POS:'Import z POS',MANUAL:'Dodaj ręcznie',START_EMPTY:'Zacznij bez produktów'}} value={value.method} onChange={(x:string)=>set({method:x})}/>{value.method==='CSV_EXCEL'&&<div className="mt-5 p-4 rounded-xl bg-blue-50"><p className="text-sm text-blue-900 mb-3">Plik CSV powinien zawierać kolumny: <b>sku, ean, name, purchase_price, selling_price</b>. Przed zapisem zobaczysz podgląd. Istniejące SKU i EAN zostaną pominięte.</p><input type="file" accept=".csv,text/csv" onChange={(e)=>e.target.files?.[0]&&load(e.target.files[0])}/>{preview&&<div className="mt-4"><p className="text-sm font-medium">Poprawne: {preview.valid} · Pominięte: {preview.invalid}</p><div className="max-h-40 overflow-auto mt-2 text-xs">{preview.rows?.slice(0,20).map((r:any)=><div key={r.row} className={`py-1 ${r.valid?'text-gray-700':'text-red-700'}`}>{r.row}. {r.sku} — {r.name} {r.errors?.join(', ')}</div>)}</div><button type="button" disabled={!preview.valid} onClick={run} className="mt-3 px-4 py-2 rounded-xl bg-blue-700 text-white disabled:opacity-40">Importuj poprawne pozycje</button>{message&&<p className="mt-2 text-green-700 font-medium">{message}</p>}</div>}</div>}</>
}
